# Generated by Django 4.1.2 on 2023-06-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='idMarca', primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id_talla', models.AutoField(db_column='idTalla', primary_key=True, serialize=False)),
                ('talla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('id_marca', models.ForeignKey(db_column='idMarca', on_delete=django.db.models.deletion.CASCADE, to='productos.marca')),
                ('id_talla', models.ForeignKey(db_column='idTalla', on_delete=django.db.models.deletion.CASCADE, to='productos.talla')),
            ],
        ),
    ]
